project:
  type: website
  output-dir: docs
  resources:
    - sta199-f22-1-syllabus.pdf
    - slides/27-interactive-web-apps.pdf

website:
  page-navigation: true
  title: "CSC 110"
  description: "Homepage for CSC 110 - Data Science & Society at Davidson College, Spring 2025"
  site-url: "https://sta199-f22-1.github.io/"

  repo-url: https://github.com/pebenbow/csc110-202402.github.io
  repo-actions: [issue]

  open-graph: true

  sidebar:
    background: "#d42121"
    logo: "images/davidson-wordmark-lockup-on red.png"
    logo-alt: "Davidson College wordmark"
    pinned: true
    title: "CSC 110"
    align: center

    tools:
      - icon: github
        href: https://github.com/sta199-f22-1/sta199-f22-1.github.io
        text: "GitHub organization"

    style: docked
    search: true
    collapse-level: 2
    contents:
      - section: "Course information"
        contents:
          - href: index.qmd
            text: Schedule
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-team.qmd
            text: Instructional team
          - href: course-support.qmd
            text: Support
          - href: course-links.qmd
            text: Useful links
          - href: course-faq.qmd
            text: FAQ
      - section: "Resources"
        contents:
          - href: https://csc110.jupyter.davidson.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fpebenbow%2FCSC110-202401&urlpath=rstudio%2F&branch=main
            text: JupyterHub
          - href: https://www.gradescope.com/courses/815355
            text: Gradescope
          - href: https://r4ds.hadley.nz/
            text: R4DS
      - section: "Project"
        contents:
          - href: project-description.qmd
            text: Description
          - href: project-tips-resources.qmd
            text: Tips + resources

  page-footer:
    left: "Course website adapted from STA-199 at Duke University"
    right: "This page is built with [Quarto](https://quarto.org/)"
    background: "#000000"

format:
  html:
    theme:
      light: [cosmo, style/sta199.scss]
      dark: [cosmo, style/sta199.scss, style/dark.scss]
    linkcolor: "#d42121"
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"

execute:
  freeze: auto

editor: visual
