---
title: "Course support"
toc: true
toc-depth: 3
---

Most of you will need help at some point and we want to make sure you can identify when that is without getting too frustrated and feel comfortable seeking help.

## In class

If you have a question during class, please ask!
I can almost guarantee there are other students in class with the same question, so you will create a learning opportunity for everyone if you raise your hand.

## Outside class

There are tons of resources available if you have questions outside of class.
I've outlined them below in no particular order.

### Slack

Have a question that can't wait for office hours?
Prefer to write out your question in detail rather than asking in person?
The course Slack is the best venue for these!
There is a chance another student has already asked a similar question, so please check the other posts on Slack before asking a new question.
If you know the answer to a question that is posted, I encourage you to respond!

### Office hours

I keep weekly office hours for all courses I teach.
While I prefer to meet in-person, I also have an option for virtual office hours to be held via Zoom if one of us is sick or "geographically challenged" for any reason.

To see my office hours and schedule an appointment, please see the [instructional team page](course-team.qmd).

### Embedded tutor

This class has an embedded tutor who took CSC 110 previously and is offering their time and experience to help students in this class.
For details on this person's office hours and contact info, please see the [instructional team page](course-team.qmd).

### Data CATS

The **Data CATS team** is a group of student data consultants, many of whom have experience with R and statistics.
They have drop-in office hours in Chambers 3146 most days of the week, plus you can sometimes schedule individual appointments.
For more information, including the consultants' availability and contact info, please go to the [Data CATS website](https://www.davidson.edu/offices-and-services/center-teaching-and-learning/student-resources/data-cats).

### Email

Emailing me is best when you have questions that are personal in nature or protected under FERPA, such as about illness, accommodations, your individual performance in this class, etc.
If you have a general question about course content that is not specific to yourself, you should post that in the #general channel in our Slack workspace.

Barring extenuating circumstances, I will respond to emails within 48 hours Monday - Friday.
Response time may be slower for emails sent Friday evening - Sunday.

## Academic support

There are times may need help with the class that is beyond what can be provided by the teaching team.
In those instances, I encourage you to visit the Academic Resource Center.
The [Academic Resource Center (ARC)](https://arc.duke.edu) offers free services to all students during their undergraduate careers at Duke.
Services include Learning Consultations, Peer Tutoring and Study Groups, ADHD/LD Coaching, Outreach Workshops, and more.
Because learning is a process unique to every individual, they work with each student to discover and develop their own academic strategy for success at Duke.
Contact the ARC to schedule an appointment.
Undergraduates in any year, studying any discipline can benefit!
Contact [ARC\@duke.edu](mailto:arc@duke.edu), 919-684-5917.

## Mental health and wellness

If your mental health concerns and/or stressful events negatively affect your daily emotional state, academic performance, or ability to participate in your daily activities, many resources are available to help you through difficult times. 
Duke encourages all students to access these resources.

## **Assistance with Zoom**

For technical help with Sakai or Zoom, contact the Duke OIT Service Desk at [oit.duke.edu/help](https://oit.duke.edu/help).
You can also access the self-service help documentation for Zoom [here](https://oit.duke.edu/help/articles/kb0029318) and for Sakai [here](https://sakai-duke.screenstepslive.com/s/sakai_support).

Zoom will be used for online office hours as well as as a backup option should we need to hold the course online instead of in person.

<link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">

```{=html}
<script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript" async></script>
```

```{=html}
<script type="text/javascript">window.onload = function() { Calendly.initBadgeWidget({ url: 'https://calendly.com/pete-benbow/csc-110-office-hours', text: 'Schedule office hours', color: '#d42121', textColor: '#ffffff' }); }</script>
```
