---
title: "Syllabus"
number-sections: true
---

::: {.content-visible when-format="html"}
[**Click here**](sta199-f22-1-syllabus.pdf) **to download a PDF copy of the syllabus.**
:::

# Course overview

This course is an introduction to data science explored through the lens of contemporary economic and social justice issues.
Using the R statistical programming language, you will learn to manipulate, visualize, and analyze data for the purpose of understanding societal phenomena and patterns that impact the lives of people in the United States.
You will also learn to effectively communicate data science topics by researching, writing, and presenting on real-world problems, using data throughout the process to inform your analysis and support your findings.

## Curricular connections

This course satisfies the graduation requirement in Justice, Equality, and Community (JEC).
It is also an introductory elective course for the Data Science minor, and satisfies the Mathematical & Quantitative Thought distribution requirement for graduation.

## Prerequisites

This is an introductory course to data science.
There are no prerequisites.
I will assume no previous experience with R, computer programming or any other aspect of data science.

## Learning outcomes

Together, we will strive for your individual and collective success in achieving the learning outcomes of this course.
At the conclusion of this course, students will be able to:

-   Define and describe the varied nature of data and data science

-   Describe and discuss ethical issues in the practice of data science

-   Organize and clean data using R

-   Communicate clearly and persuasively with data, using accurate, unbiased and aesthetically pleasing visualizations

-   Apply data science methods to illuminate and analyze issues of injustice or structural inequality  

# Course materials & tools

The main material for learning R in this course is [R for Data Science (R4DS), 2nd edition](https://r4ds.hadley.nz/), a freely available online textbook.
Hard copies of R4DS are available from [Amazon](https://www.amazon.com/Data-Science-Transform-Visualize-Model/dp/1492097403) and [Bookshop.org](https://bookshop.org/p/books/r-for-data-science-import-tidy-transform-visualize-and-model-data-hadley-wickham/19667446?ean=9781492097402) if you want to order one, but it is not required for this course.
Other minor reading and materials will be distributed throughout the semester via assignments.

# Statement on usage of AI tools

Generative artificial intelligence (AI) can be a huge asset to data scientists, especially for code generation.
I use it all the time!
However, AI does not always produce correct output, and it should not be used as a crutch.
It is only a matter of time before you need to fix the code it generates for you, and it’s a lot easier to do that when you know the language.
Also, many employers require “coding interviews” during the application process where you’ll be expected to write code and produce results in a proctored environment without the aid of AI tools.
So you need to learn how to code from scratch.

As such, **I expect that you will not use AI tools such as ChatGPT, Claude, Copilot, etc. for this course unless I explicitly allow it on certain assignments**.
There will be a few assignments where I will actively encourage the use of generative AI, and I’m excited to gather your reflections on that experience.
Otherwise, it is safe to assume that you should not use generative AI tools in this course.
**When in doubt, just ask me.**

# Course community

## Student success

Every student’s success is important to me.
The components of the course require a range of skills and abilities, all designed to maximize your opportunities to grow and learn.
I am happy to work with you to develop strategies that will meet your needs while fulfilling the requirements of the course.
Programming can only be learned with repeated, hands-on practice.
**It is normal and expected that all students will need help inside and outside of class with the material in this course.** This course is structured to reward you for experimenting, learning from your mistakes, and seeking help. 

## Attendance policy

Out of respect for me and your classmates, please show up to class on time.
You are expected to attend and engage in class every day unless you are sick.
I adhere to the [college’s policy](https://www.davidson.edu/offices-and-services/registrar/academic-regulations) that any student missing more than 25% of course meetings will be assigned an F for their final grade.
This class meets 28 times this semester, so that means you are only able to miss up to 7 days of class.
However, you may be given allowed absences for religious observances, athletic travel, family obligations, or other extenuating circumstances on a case-by-case basis.
I expect to be notified at least one week in advance of any planned absences, so please look carefully at your schedule and notify me if there are any such conflicts during the semester.
Furthermore, if the due date for an assignment conflicts with an excused absence, you can request appropriate accommodations such as taking the assignment early or requesting an extension.

## Late work policy

Everyone is granted five “slip days” at the beginning of the semester.
This means you have five days, total, to submit late assignments and still receive full credit.
You can use all five days on one assignment or use one day for each of five assignments, etc.
Please use these wisely.
Do not use all of your slip days at the beginning of the semester because if you have an emergency at the end of the semester, I will not grant more slip days.
Each day an assignment is late without slip days, you will receive a 10% penalty on your grade.

## The Honor Code

You may discuss homework assignments with your small group, and you may ask me and peer tutors (see [Learning support]) for help.
You may not seek help from any other source.
Quizzes are to be done individually, and with specified resources only.
Projects must be done with your small group, with authorized resources only.
**You are required to pledge all graded assignments under the Honor Code.** Failure to pledge an assignment by its due date will result in an automatic 10% penalty on the final grade.
In other words, if you are completing a quiz that is graded on a 100-point scale and you score a 93, but you fail to sign the Honor Code pledge, your score will be reduced to an 83.

## Access and accommodation

Davidson welcomes requests for accommodations related to disability and will grant those that are determined to be reasonable and maintain the integrity of a program or curriculum.
To make such a request or to begin a conversation about a possible request, please contact the Office of Academic Access and Disability Resources by emailing [AADR\@davidson.edu](mailto:aadr@davidson.edu?subject=Accessibility%20request).
It is best to submit accommodation requests within the drop/add period; however, requests can be made at any time in the semester. 
Please keep in mind that accommodations are not retroactive.

## Learning support

Your primary source of peer learning support and assistance for this course should be our embedded tutor.
For contact information and office hours

Your secondary source of support should be through Data CATS. Students can drop by anytime during open office hours, or they can contact Dr. Laurie Heyer about setting up an appointment.
We are located in **Chambers 3146** and have drop-in hours from **2-4pm and 7-9pm Sundays - Thursdays.** 

The Math & Science Center (MSC) will also have a small number of additional peer tutors available on a drop-in or by-appointment basis.
The embedded, drop-in, and by-appointment tutors are trained and highly qualified peers that demonstrated deep understanding and succeeded in this course themselves.
Located in the Center for Teaching & Learning (CTL) on the first floor of the College Library, the MSC’s drop-in hours are Sunday through Thursday, 8-11 PM, beginning Sunday, August 25.
Prior to visiting for drop-in help, be sure to look at the tutor schedules to determine when an appropriate tutor for your course/topic will be present.
Tutor schedules for drop-in assistance, as well as links to schedule an appointment with a tutor, can be found [here](https://www.davidson.edu/offices-and-services/center-teaching-and-learning/student-resources/math-science-and-economics-center) (click on “Meet with Math or Science Tutor”).
Peer assistance is free to Davidson students at the point of service.
For more information, contact Dr. Mark Barsoum, Director of the CTL (mabarsoum or ext. 2796).

## Anti-oppression

I am committed to creating and sustaining an inclusive and equitable learning environment for all students.
I recognize racism, sexism, classism, ableism, heterosexism, and cisgenderism as systems of oppression that affect our whole society and communities like our classroom.
Some people are affected more than others, particularly individuals at the intersection of multiple groups.

I acknowledge my own power and privilege as a White person, an aspect of my identity that has made success in data science easier for me than for Black, Indigenous, and People of Color (BIPOC) individuals, who have been historically excluded from related disciplines.
I am committed to the ongoing and iterative work of developing personal and institutional practices of anti-oppression, including what and how I teach.

I invite you to join me and support me in this work by communicating respectfully, consistently and proactively identifying and confronting oppressive behaviors in yourself and others, and seeking to understand ways in which data science can improve society and the lives of BIPOC individuals.
I welcome your feedback and suggestions about these commitments and others you would like us to make to each other.

# Grading

The final course grade for this course will be calculated using the following weights:

| Components                  | Percentage of final grade |
|-----------------------------|---------------------------|
| Weekly homework assignments | 10%                       |
| Labs                        | 35%                       |
| Quizzes                     | 30%                       |
| Capstone project            | 25%                       |

## Letter grades

The letter grade for this course will be determined based on the following thresholds:

| Letter grade | Final course grade | GPA equivalent value |
|--------------|--------------------|----------------------|
| A            | \>= 93             | 4.0                  |
| A-           | 90 - 92.99         | 3.7                  |
| B+           | 87 - 89.99         | 3.3                  |
| B            | 83 - 86.99         | 3.0                  |
| B-           | 80 - 82.99         | 2.7                  |
| C+           | 77 - 79.99         | 2.3                  |
| C            | 73 - 76.99         | 2.0                  |
| C-           | 70 - 72.99         | 1.7                  |
| D+           | 67 - 69.99         | 1.3                  |
| D            | 60 - 66.99         | 1.0                  |
| F            | \< 60              | 0.0                  |

<link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">

```{=html}
<script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript" async></script>
```

```{=html}
<script type="text/javascript">window.onload = function() { Calendly.initBadgeWidget({ url: 'https://calendly.com/pete-benbow/csc-110-office-hours', text: 'Schedule office hours', color: '#d42121', textColor: '#ffffff' }); }</script>
```
