---
title: "CSC 110: Data Science & Society"
subtitle: "Spring 2025"
execute:
  freeze: false
---

This page contains an outline of the topics, content, and assignments for the semester.

Note that this schedule will be updated as the semester progresses and the timeline of topics and assignments might be updated throughout the semester.

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(googlesheets4)
library(gt)
library(tidyverse)
gs4_deauth()
d <- read_sheet("https://docs.google.com/spreadsheets/d/13CvB0DEuuKvst--9pZ_7oNwB06qPAiwa07bEUxarf7g/edit?usp=sharing", sheet = "Sheet1")
```

::: column-screen-right
```{r, echo = FALSE}
d |>
  mutate(
    date = as.Date(date)
  ) |>
  gt() |>
  text_transform(cells_body(columns = c(prepare)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("book", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('book')}</a>")
      )
    }
  ) |>
  text_transform(cells_body(columns = c(slides)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("laptop", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('display')}</a>")
      )
    }
  ) |>
  text_transform(cells_body(columns = c(ex)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("users", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('users')}</a>")
      )
    }
  ) |>
  text_transform(cells_body(columns = c(ae_sa)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("key", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('key')}</a>")
      )
    }
  ) |>
  text_transform(cells_body(columns = c(hw)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("keyboard", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('keyboard')}</a>")
      )
    }
  ) |>
  text_transform(cells_body(columns = c(hw_sa)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("key", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('key')}</a>")
      )
    }
  ) |>
  text_transform(cells_body(columns = c(lab)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("users-rectangle", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('users-rectangle')}</a>")
      )
    }
  ) |>
  text_transform(cells_body(columns = c(lab_sa)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("key", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('key')}</a>")
      )
    }
  ) |>
  text_transform(cells_body(columns = c(exam)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("file-circle-check", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('file-circle-check')}</a>")
      )
    }
  ) |>
  text_transform(cells_body(columns = c(project)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("users", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('users')}</a>")
      )
    }
  ) |>
  fmt_date(date, date_style = 30) |>
  sub_missing(columns = c(date, topic, notes), missing_text = "") |>
  cols_align(
    align = "center", 
    columns = c(prepare, slides, ex, ae_sa, hw, hw_sa, lab, lab_sa, exam, project)
    ) |>
  cols_align(
    align = "left", 
    columns = c(day, date, topic, notes)
    ) |>
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "#D3D3D3",
      style = "solid"
    ),
    locations = cells_body(
      columns = c(date, day, topic, prepare, ae_sa, hw_sa, lab_sa, exam, project)
    )
  ) |>
  tab_style(
    style = cell_fill(color = "white"),
    locations = cells_body(
      rows = topic %in% c("Spring Break", "Fall Break")
    )
)
```
:::

<link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">

<script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript" async></script>
<script type="text/javascript">window.onload = function() { Calendly.initBadgeWidget({ url: 'https://calendly.com/pete-benbow/csc-110-office-hours', text: 'Schedule office hours', color: '#d42121', textColor: '#ffffff' }); }</script>